// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ReceiveResult {
  final BigInt fileCount;
  final BigInt size;
  final BigInt durationMs;

  const ReceiveResult({
    required this.fileCount,
    required this.size,
    required this.durationMs,
  });

  @override
  int get hashCode => fileCount.hashCode ^ size.hashCode ^ durationMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReceiveResult &&
          runtimeType == other.runtimeType &&
          fileCount == other.fileCount &&
          size == other.size &&
          durationMs == other.durationMs;
}

class SendResult {
  final String ticket;
  final String hash;
  final BigInt size;
  final BigInt fileCount;

  const SendResult({
    required this.ticket,
    required this.hash,
    required this.size,
    required this.fileCount,
  });

  @override
  int get hashCode =>
      ticket.hashCode ^ hash.hashCode ^ size.hashCode ^ fileCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SendResult &&
          runtimeType == other.runtimeType &&
          ticket == other.ticket &&
          hash == other.hash &&
          size == other.size &&
          fileCount == other.fileCount;
}
